// AUTO-GENERATED by scripts/build-engine.mjs — do not hand-edit. Content hash of each
// contract bundle, appended to its fetch URL by engine.ts so an HTTP-cached bundle can
// never be served to a .wasm built against a different schema. Workbox is told to ignore
// the `v` parameter (vite.config.ts `ignoreURLParametersMatching`), so the precached
// entry still matches and offline loads are unaffected.

export const ENGINE_BUNDLE_VERSIONS: Record<string, string> =
  {
    "brainstorm": "bb95e93c3d88d802",
    "homecoming": "151f415de0526691",
    "rebirth": "7263af2536614cd2",
    "thunderspy": "9dab8120f7f1aa79"
  };
