// AUTO-GENERATED by scripts/build-engine.mjs — do not hand-edit. Content hash of each
// contract bundle, appended to its fetch URL by engine.ts so an HTTP-cached bundle can
// never be served to a .wasm built against a different schema. Workbox is told to ignore
// the `v` parameter (vite.config.ts `ignoreURLParametersMatching`), so the precached
// entry still matches and offline loads are unaffected.

export const ENGINE_BUNDLE_VERSIONS: Record<string, string> =
  {
    "brainstorm": "383ba146f86a3bb4",
    "homecoming": "326e38e3db85ff74",
    "rebirth": "b005b19841d75a6f",
    "thunderspy": "c69afb6cc1857a23"
  };
